### ISSUE TITLE
您好，想咨询下 您之前标定了odom和cam的外参

### ISSUE THREAD

**Issue by yuyadanyadan** [extr15/slam_note#3]
我看到您在https://github.com/hengli/camodocal项目里面留言了， 您是不是也用的CamOdomCalibration进行里程计和相机的标定？我最近这几天都在尝试用它标定，但是标定出来的结果完全不对，但是我尝试用里程计的数据乘以一个固定外参，输进去，就可以标定出这个固定外参，不知道是不是我的图像的位姿数据太差还是怎么的？ 希望您能帮助我一下，非常感谢！

**Comment by rising-turtle** [comment]
Hi:

比较推荐这个https://github.com/ethz-asl/kalibr 来做 cam-odo calibration. 另外, 你的
camera 是不是 rolling-shutter 还是 global shutter, 如果是 rolling-shutter,
可能结果也不会特别精确, 记得要加上 time-synchronization. 我的camera 是rolling shutter
的,所以只是得到了一个大概的外参, 不是特别精确, 然后跑的是 VINS-Mono 利用它的 initialization 来refine
CAM-ODO Transformation.
see the discussion here https://github.com/ethz-asl/kalibr/issues/111

Best,

He




2018-08-28 4:09 GMT-04:00 yuyadanyadan <notifications@github.com>:

**Comment by yuyadanyadan** [comment]
首先，我的结果不是不精确，而是完全不对，一直没找到原因！   我的图像的位置是用orb-slam2跑出来的结果，然后对应里程计的数据是插值出来的结果，我一直很困惑是什么原因，输进去的位置是前一帧到当前帧的位置。 kalibr还可以用来标定cam-odom? q请问可以加下您qq么？万分感谢！！！我qq是1553532009,  谢谢， 麻烦了，旁边实在是没有做过这个标定的伙伴

**Comment by yuyadanyadan** [comment]
而且我的两种位姿用rviz显示过了  形状都是一样的， 就是走过的路径的形状是一样的

**Comment by yuyadanyadan** [comment]
我的cam是global-shutter, 几组不同数据标定出来的效果不同，而且那个motionCount和segmentCount您是依据什么来设置的？我直接设置motionCount = 10;  如果用kalibr来标的话，是不是需要把里面关于Imu的部分改成odom??? 希望您能回复我，谢谢

**Comment by rising-turtle** [comment]
Hi 如果是global-shutter 应该是可以的， 你先自己折腾一下，说不定就弄出来了， 最近有个deadline在九月底，
如果十月初的时候还没弄好，把采好的数据发给我 帮你
调一下



2018-09-04 0:46 GMT-07:00 yuyadanyadan <notifications@github.com>:

**Comment by yuyadanyadan** [comment]
Hi  
  谢谢，麻烦你了！我测出来的结果不够准确， 
将图像和odometry数据扔进去，图像通过他自身的vo计算出的位姿； 得出的结果(result1)与利用他给出的CamOdoCalibration_test中将orbslam2的图像位姿和odometry扔进去的结果(result2)进行了一下比较，旋转差不多，只有yaw差了几度，roll和pitch都在1度以下； 平移的x相差在1cm以下，但是它计算的y,跟我的差距较大，我计算出来的是7cm， 他算出来的是-28cm; 
result1:
H_cam_odo =
  0.0740025   0.0103076    0.997205   0.0293397
    -0.9972 -0.00999095   0.0741055   -0.281613
  0.0107269   -0.999897  0.00953939           0
          0           0           0           1
r p y: -89.4535 -0.614617 -85.7559

result2:
Rotation:
   0.171076   0.0196879    0.985061
  -0.985228 -0.00435906    0.171192
 0.00766435   -0.999797   0.0186513
Translation:
0.0330635 0.0799669         0
RPY: -88.9   -0.4    -80.5

因为在网上找的开源数据， 所以我这有较为准确的外参：
- Translation: [0.074, 0.030, 1.251]
- Rotation: in Quaternion [0.491, -0.509, 0.509, -0.490]
            in RPY (radian) [-1.571, -0.001, -1.608]
            in RPY (degree) [-90.028, -0.035, -92.113]

感觉算出来的结果都不够准确呢。。。
谢谢哈， 你先忙你的

**Comment by extr15** [comment]
@yuyadanyadan ,sorry for the late. In my impression, VO of `camodocal` is not that good, you said the trajectory of odom and VO was the same shape and you knew the extrinsic already, maybe you can use the extrinsic to check the error between the odom trajectory and VO trajectory?

**Comment by yuyadanyadan** [comment]
thank you, I use the result of ORB-SLAM2 not its own vo. And I get the almost accurate result, Thank you very much!

**Comment by bcWorkAccount** [comment]
你好，我使用camodocal标定结果不是最优的，请问你的是吗？

**Comment by bcWorkAccount** [comment]
@yuyadanyadan
